#Configuration Midgar Application
#Tue May 05 14:18:58 CET 2026
app.name=Midgar
app.title=Plateforme de Cr\u00E9ation Fantasy
app.version=1.0.0
db.password=
db.persistent=true
db.type=MySQL
db.url=jdbc\:mysql\://localhost\:3306/midgar37?useSSL\=false&serverTimezone\=UTC&allowPublicKeyRetrieval\=true
db.user=root
debug.enabled=true
debug.verbose=false
ui.height=800
ui.theme=dark
ui.width=1200
