package com.example.app.services;

import java.util.Map;

/**
 * Holds the output of the explanation process.
 *
 * - explanation : human-readable text generated by Groq (or the fallback constant)
 * - scores      : the raw score breakdown forwarded from the RankedPost
 */
public class WhyResult {

    private final String              explanation;
    private final Map<String, Double> scores;

    public WhyResult(String explanation, Map<String, Double> scores) {
        this.explanation = explanation;
        this.scores      = scores;
    }

    /** The AI-generated (or fallback) explanation string. */
    public String getExplanation() { return explanation; }

    /** tag_similarity, engagement_score, recency_decay, behavior_similarity → 0..1 */
    public Map<String, Double> getScores() { return scores; }

    @Override
    public String toString() {
        return "WhyResult{explanation='" + explanation + "', scores=" + scores + '}';
    }
}